// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          're-run FlutterFire CLI to configure it.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          're-run FlutterFire CLI to configure it.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          're-run FlutterFire CLI to configure it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJHNLxVEDu4vGdm2RM_yn-Kd-laE2Iwg',
    appId: '1:742928632721:web:db1facec490e8b5a77e830',
    messagingSenderId: '742928632721',
    projectId: 'environment-monitoring-s-c26ff',
    authDomain: 'environment-monitoring-s-c26ff.firebaseapp.com',
    storageBucket: 'environment-monitoring-s-c26ff.appspot.com',
    measurementId: 'G-WHG8ELD6S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi_mAF0-902Vogq3KUrLx7t3ZJvyxgqMA',
    appId: '1:742928632721:android:a98292a3bdfe6c4177e830',
    messagingSenderId: '742928632721',
    projectId: 'environment-monitoring-s-c26ff',
    storageBucket: 'environment-monitoring-s-c26ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK0Rct1QvdHLcUEaXVCTjwESbStbQtBgY',
    appId: '1:742928632721:ios:ee98dfba470675e777e830',
    messagingSenderId: '742928632721',
    projectId: 'environment-monitoring-s-c26ff',
    storageBucket: 'environment-monitoring-s-c26ff.appspot.com',
    iosBundleId: 'com.example.envMonitoringDashboard',
  );
}
